=== Enryu99/L2jMobius-01-11/L2J_Mobius_C4/dist/game/data/xsd/multisell.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="ingredient">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="id" use="optional"/>
											<xs:attribute type="xs:int" name="count" use="optional"/>
											<xs:attribute type="xs:byte" name="enchant" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="production">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="id" use="optional"/>
											<xs:attribute type="xs:int" name="count" use="optional"/>
											<xs:attribute type="xs:byte" name="enchant" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute type="xs:int" name="id" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="maintainEnchantment" use="optional"/>
			<xs:attribute type="xs:string" name="applyTaxes" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Enryu99/L2jMobius-01-11/L2J_Mobius_Essence_4.0_DwellingOfSpirits/dist/game/data/multisell/3025406.xml
<?xml version="1.0" encoding="UTF-8"?>
<list isChanceMultisell="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>30254</npc> <!-- Harmony -->
	</npcs>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="91483" count="1" /> <!-- Scroll: Bind --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90089" count="1" /> <!-- Scroll: Vampiric Mist --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90083" count="1" /> <!-- Scroll: Ice Vortex Crusher --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90086" count="1" /> <!-- Scroll: Arcane Shield --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90085" count="1" /> <!-- Scroll: Arcane Chaos --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90081" count="1" /> <!-- Scroll: Arcane Power --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90084" count="1" /> <!-- Scroll: Wind Vortex Slug --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90087" count="1" /> <!-- Scroll: Curse of Doom --> 
	</item>
	
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90088" count="1" /> <!-- Scroll: Curse of Abyss --> 
	</item>
	<item>
		<ingredient id="90045" count="31" /> <!-- Magical Tablet --> 
		<ingredient id="57" count="100000" /> <!-- Adena --> 
		<production id="90082" count="1" /> <!-- Scroll: Fire Vortex Buster --> 
	</item>
</list>

=== Enryu99/L2jMobius-01-11/L2J_Mobius_Test/dist/game/data/multisell/3247802.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>32478</npc> <!-- Dimensional Manager -->
	</npcs>
	<item>
		<!-- Immortal Armor Set Coupon -->
		<ingredient count="1" id="27526" />
		<!-- Immortal Armor Heavy Set --> 
	    <!-- Official not work! isn't confirmed -->
		<production count="1" id="17304" />
		<production count="1" id="17305" />
		<production count="1" id="17306" />
		<production count="1" id="17307" />
		<production count="1" id="17308" />
	</item>
</list>

=== Enryu99/L2jMobius-01-11/trunk/dist/game/data/multisell/custom/600024.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/multisell.xsd">
	<item>
		<ingredient id="57" count="10000000"/>
		<production id="1419" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="20000000"/>
		<production id="3874" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="40000000"/>
		<production id="3870" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="1"/>
		<production id="4295" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="1"/>
		<production id="3865" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="8000000"/>
		<production id="8056" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="10000"/>
		<production id="7609" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="50000"/>
		<production id="7256" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="50000"/>
		<production id="7257" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="50000"/>
		<production id="7258" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="50000"/>
		<production id="7259" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="8073" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="7215" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="7225" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="7243" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="7219" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="7267" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="25"/>
		<production id="15307" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="25"/>
		<production id="15308" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="25"/>
		<production id="15309" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9714" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9687" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9686" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9685" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9691" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="500000"/>
		<production id="9690" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="8275" count="1"/>
	</item>
	<item>
		<ingredient id="57" count="100000"/>
		<production id="8056" count="1"/>
	</item>
</list>

=== Enryu99/L2jMobius-01-11/L2J_Mobius_C6_Interlude/dist/game/data/multisell/30847.xml
<?xml version='1.0' encoding='utf-8'?> 
<!-- Exchange of Ferris (level 1) -->
<list maintainEnchantment="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<!-- 5 G Wyrm + 5 G Giant -> 1 G Dragon -->
	<item id="1">
		<ingredient id="3486" count="5" />
		<ingredient id="3484" count="5" />
		<production id="3481" count="1" />
	</item>
	<!-- 5 B Succubus + 5 B Basilisk -> 1 B Dragon -->
	<item id="2">
		<ingredient id="3476" count="5" />
		<ingredient id="3474" count="5" />
		<production id="3477" count="1" />
	</item>
	<!-- 5 S Dryad + 5 S Undine -> 1 S Dragon -->
	<item id="3">
		<ingredient id="3492" count="5" />
		<ingredient id="3495" count="5" />
		<production id="3493" count="1" />
	</item>
	<!-- 10 B Succubus + 10 B Basilisk -> 1 Beleth Blood -->
	<item id="4">
		<ingredient id="3476" count="10" />
		<ingredient id="3474" count="10" />
		<production id="3478" count="1" />
	</item>
	<!-- 1 Beleth Blood + 1 S Dragon + 13 G Wyrm -> Demon Staff -->
	<item id="5">
		<ingredient id="3478" count="1" />
		<ingredient id="3493" count="1" />
		<ingredient id="3486" count="13" />
		<production id="206" count="1" />
	</item>
	<!-- 1 Beleth Gold + 1 B Dragon + 1 S Dryad + 1 G Giant -> Dark Screamer -->
	<item id="6">
		<ingredient id="3487" count="1" />
		<ingredient id="3477" count="1" />
		<ingredient id="3492" count="1" />
		<ingredient id="3484" count="1" />
		<production id="233" count="1" />
	</item>
	<!-- 1 Beleth Silver + 1 G Dragon + 1 B Succubus + 1 B Basilisk -> Widow maker -->
	<item id="7">
		<ingredient id="3496" count="1" />
		<ingredient id="3481" count="1" />
		<ingredient id="3476" count="1" />
		<ingredient id="3474" count="1" />
		<production id="303" count="1" />
	</item>
	<!-- 1 S Dragon + 1 G Dragon + 1 B Dragon + 1 S Undine -> Sword of Limit -->
	<item id="8">
		<ingredient id="3493" count="1" />
		<ingredient id="3481" count="1" />
		<ingredient id="3477" count="1" />
		<ingredient id="3495" count="1" />
		<production id="132" count="1" />
	</item>
	<!-- 1 Beleth Silver + Beleth Gold + 1 B Dragon -> Ecliptic Sword -->
	<item id="9">
		<ingredient id="3496" count="1" />
		<ingredient id="3487" count="1" />
		<ingredient id="3477" count="1" />
		<production id="7888" count="1" />
	</item>
</list>
