=== Enryu99/L2jMobius-01-11/L2J_Mobius_C4/dist/game/data/xsd/weapon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="item"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="for"/>
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:integer"/>
			<xs:attribute name="name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="for">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="sub"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="add"/>
					<xs:element ref="enchant"/>
					<xs:element ref="mul"/>
					<xs:element ref="set"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sub">
		<xs:complexType>
			<xs:attribute name="order" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="stat" use="required" type="xs:NCName"/>
			<xs:attribute name="val" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="add">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="and"/>
			</xs:sequence>
			<xs:attribute name="order" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="stat" use="required" type="xs:NCName"/>
			<xs:attribute name="val" use="required" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="enchant">
		<xs:complexType>
			<xs:attribute name="order" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="stat" use="required" type="xs:NCName"/>
			<xs:attribute name="val" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mul">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="and"/>
			</xs:sequence>
			<xs:attribute name="order" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="stat" use="required" type="xs:NCName"/>
			<xs:attribute name="val" use="required" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="and"/>
			</xs:sequence>
			<xs:attribute name="order" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="stat" use="required" type="xs:NCName"/>
			<xs:attribute name="val" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="and">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="game"/>
				<xs:element ref="player"/>
				<xs:element ref="using"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="game">
		<xs:complexType>
			<xs:attribute name="chance" use="required" type="xs:integer"/>
			<xs:attribute name="skill" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="player">
		<xs:complexType>
			<xs:attribute name="hp" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="using">
		<xs:complexType>
			<xs:attribute name="slotitem" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Enryu99/L2jMobius-01-11/L2J_Mobius_C4/dist/game/data/stats/weapon/7800-7899.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/weapon.xsd">
<item id='7810' name="soulfire_dirk_mana_up">
  <for>
    <set val='86' order='0x08' stat='pAtk'/>
    <set val='91' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7811' name="soulfire_dirk_magic_hold">
  <for>
    <set val='86' order='0x08' stat='pAtk'/>
    <set val='91' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7812' name="soulfire_dirk_magic_silence">
  <for>
    <set val='86' order='0x08' stat='pAtk'/>
    <set val='91' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7813' name="hell_knife_magic_regeneration">
  <for>
    <set val='122' order='0x08' stat='pAtk'/>
    <set val='122' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7814' name="hell_knife_mental_shield">
  <for>
    <set val='122' order='0x08' stat='pAtk'/>
    <set val='122' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7815' name="hell_knife_magic_weakness">
  <for>
    <set val='122' order='0x08' stat='pAtk'/>
    <set val='122' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7816' name="apprentice_adventurers_staff">
  <for>
    <set val='23' order='0x08' stat='pAtk'/>
    <set val='22' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='325' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7817' name="apprentice_adventurers_bone_club">
  <for>
    <set val='24' order='0x08' stat='pAtk'/>
    <set val='17' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7818' name="apprentice_adventurers_knife">
  <for>
    <set val='21' order='0x08' stat='pAtk'/>
    <set val='17' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7819' name="apprentice_adventurers_cestus">
  <for>
    <set val='29' order='0x08' stat='pAtk'/>
    <set val='17' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='325' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7820' name="apprentice_adventurers_bow">
  <for>
    <set val='49' order='0x08' stat='pAtk'/>
    <set val='17' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='293' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7821' name="apprentice_adventurers_long_sword">
  <for>
    <set val='24' order='0x08' stat='pAtk'/>
    <set val='17' order='0x08' stat='mAtk'/>
    <set val='8' order='0x08' stat='rCrit'/>
    <add val='0' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7822' name="travelers_mace">
  <for>
    <set val='41' order='0x08' stat='pAtk'/>
    <set val='43' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7823' name="travelers_dark_elven_bow">
  <for>
    <set val='105' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='293' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7824' name="travelers_long_bow">
  <for>
    <set val='114' order='0x08' stat='pAtk'/>
    <set val='35' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='227' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7825' name="travelers_staff">
  <for>
    <set val='50' order='0x08' stat='pAtk'/>
    <set val='43' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='325' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7826' name="travelers_bastard_sword">
  <for>
    <set val='51' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='8' order='0x08' stat='rCrit'/>
    <add val='0' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7827' name="travelers_wand">
  <for>
    <set val='41' order='0x08' stat='pAtk'/>
    <set val='43' order='0x08' stat='mAtk'/>
    <set val='8' order='0x08' stat='rCrit'/>
    <add val='0' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7828' name="travelers_jamadhar">
  <for>
    <set val='62' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='325' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7829' name="travelers_tomahawk">
  <for>
    <set val='51' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7830' name="travelers_poniard_dagger">
  <for>
    <set val='45' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='12' order='0x08' stat='rCrit'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='433' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7831' name="travelers_pike">
  <for>
    <set val='51' order='0x08' stat='pAtk'/>
    <set val='32' order='0x08' stat='mAtk'/>
    <set val='8' order='0x08' stat='rCrit'/>
    <set val='66' order='0x08' stat='pAtkRange'/>
    <add val='-3' order='0x10' stat='accCombat'/>
    <set val='325' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
<item id='7834' name="art_of_battle_axe">
  <for>
    <set val='194' order='0x08' stat='pAtk'/>
    <set val='99' order='0x08' stat='mAtk'/>
    <set val='4' order='0x08' stat='rCrit'/>
    <add val='4' order='0x10' stat='accCombat'/>
    <set val='379' order='0x08' stat='pAtkSpd'/>
    <enchant val='0' order='0x0C' stat='pAtk'/>
    <enchant val='0' order='0x0C' stat='mAtk'/>
  </for>
</item>
</list>
